package barcode2.android.com.barcode;

/**
 * Created by Deividas on 2015-10-07.
 */

public interface Constants {

    String PRODUCTS_INFO = "PRODUCTS_INFO"; // name
    String BARCODE = "BARCODE";
    String PICTURE_ID = "PICTURE_ID";
    String FOOD_ADDITIVES_ID = "FOOD_ADDITIVES_ID";
    String BASIC_INFO_ID = "BASIC_INFO_ID";


    //BASIC FOOD_ADDITIVES_TABLE(ID, FOOD_ADDITIVES)
    String FOOD_ADDITIVES_TABLE = "FOOD_ADDITIVES_TABLE";
    String FOOD_ADDITIVES = "FOOD_ADDITIVES";


    //FOOD_ADDITIVES_MAIN_TABLE(ID, FOOD_ADDITIVES_ID, BASIC_INFO_ID)
    String FOOD_ADDITIVES_MAIN_TABLE = "FOOD_ADDITIVES_MAIN_TABLE";


    //BASIC INFO(ID, BASIC_INFO_TEXT)
    String BASIC_INFO_TABLE = "BASIC_INFO_TABLE";
    String BASIC_INFO = "BASIC_INFO";

}
